### ISSUE TITLE
Update zOSMF documetation for version 1.2.1

### ISSUE THREAD

**Issue by ddimatos** [IBM/z_ansible_collections_doc#26]
##### SUMMARY
Please generate new doc for ibm_zosmf collection using the `dev` branch where the latest RST resides. 

NOTE:
There is no change to [registry.yml](https://github.com/IBM/z_ansible_collections_doc/blob/4e0cb409c3ce88c00593036c7197cc49671bd412/registry.yml#L53) , its still pointing to their `dev` branch so its simply just running the scripts to publish the updated doc. 

##### ISSUE TYPE
- Update Collection

**Comment by ddimatos** [comment]
FYI @itsBryantP

**Comment by jennyhuang17** [comment]
I've rebuilt the doc for ibm_zosmf collection updates. 

Here's a quick preview to the release notes which include the new version 1.2.1: https://ibm.github.io/z_ansible_collections_doc/ibm_zosmf/docs/source/release_notes.html

**Comment by ddimatos** [comment]
Thank you @jennyhuang17
