### ISSUE TITLE
Update zOSMF documetation for version 1.3.0

### ISSUE THREAD

**Issue by zosmf-Robyn** [IBM/z_ansible_collections_doc#32]
SUMMARY

Please generate new doc for ibm_zosmf collection using the dev branch where the latest RST resides.

NOTE:
There is no change to [registry.yml](https://github.com/IBM/z_ansible_collections_doc/blob/4e0cb409c3ce88c00593036c7197cc49671bd412/registry.yml#L53) , its still pointing to their dev branch so its simply just running the scripts to publish the updated doc.

ISSUE TYPE

* Update Collection

**Comment by ddimatos** [comment]
@jennyhuang17 - are you able to generate the doc?

**Comment by jennyhuang17** [comment]
@ddimatos Sure. Will generate the new doc today.

**Comment by jennyhuang17** [comment]
The new doc for ibm_zosmf collection version 1.3.0 has been generated :)
