### ISSUE TITLE
Update zOSMF documetation for version 1.4.0

### ISSUE THREAD

**Issue by zosmf-Robyn** [IBM/z_ansible_collections_doc#41]
SUMMARY

Please generate new doc for ibm_zosmf collection using the dev branch where the latest RST resides.

NOTE:
There is no change to [registry.yml](https://github.com/IBM/z_ansible_collections_doc/blob/4e0cb409c3ce88c00593036c7197cc49671bd412/registry.yml#L53) , its still pointing to their dev branch so its simply just running the scripts to publish the updated doc.

ISSUE TYPE

Update Collection

**Comment by ddimatos** [comment]
Thank you,  I will do this tonight, fyi @jennyhuang17

**Comment by ddimatos** [comment]
@zosmf-Robyn - this has been completed. Thank you for the issue.
