### ISSUE TITLE
Update zOSMF documentation for version 1.5.0

### ISSUE THREAD

**Issue by zosmf-Robyn** [IBM/z_ansible_collections_doc#56]
SUMMARY

Please generate new doc for **ibm_zosmf** collection using the ``main`` branch where the latest RST resides.

ISSUE TYPE

* Update Collection

**Comment by zosmf-Robyn** [comment]
@ddimatos could you help to update this? Thanks.

**Comment by ddimatos** [comment]
@zosmf-Robyn , absolutely, this somehow got buried with so many other notifications, hope to soon automate this. 
All done, thank you.
