### ISSUE TITLE
unified documentation seems a bit broken

### ISSUE THREAD

**Issue by LUEDDEA** [IBM/z_ansible_collections_doc#7]
IMS readme shows the text of core readme:

https://ibm.github.io/z_ansible_collections_doc/ibm_zos_ims/docs/ansible_content.html

![image](https://user-images.githubusercontent.com/22913513/100373436-116c0f00-300b-11eb-95cd-e0855b21d28f.png)

**Comment by ddimatos** [comment]
Thank you Anke. It's actually an issue of the IMS collection's doc , the unified doc is only pulling that the collections publish doc. I will open a PR on the IMS then regenerate this doc , thank you for reporting

**Comment by ddimatos** [comment]
Resolved.
